# Welcome to Serverless!
service: nodeless
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - 'arn:aws:s3:::*'
  lambdaHashingVersion: 20201221

functions:
  formMailer:
    handler: index.handler
    events:
      - http:
          path: /
          method: post
          cors: true
